DSND-2337: Convert snake case to camel in transform_rules file
companieshouse/filing-history-delta-consumer pull request #18
Opened 2024-01-19 17:08 UTC by crowlandsCH

## Describe the changes
* Used regex expressions which I'll pop on the ticket to modify the yml file from snake_case to camelCase.

### Related Jira tickets
[DSND-2337](https://companieshouse.atlassian.net/browse/DSND-2337)

## Developer check list
### General
- [y] Is the PR as small as it can be?
- [y] Has the Jira ticket been updated with any relevant comments?
- [ ] Is the `README` up to date?
- [ ] Has the `POM` been updated for the latest versions of dependencies?
- [ ] Has the code been double-checked against `main`?
- [ ] Does the code adhere standards in this repository, including SonarQube checks?

### Testing
- [ ] Do the code changes have unit and integration tests with code coverage > 80%?
- [ ] Has the code been tested locally and/or passed the API Karate tests on Tilt?
- [ ] Have mandatory manual test cases been run?
- [ ] Are extra Karate tests required?
- [ ] Are all the test data resources up to date?

### Release preparation
_Where possible, add links to the respective Jira tickets when an item is checked_
- [ ] Have these changes been included in a release ticket?
- [ ] Are changes required to the `docker-chs-development` deployment or test data?
- [ ] Are any changes required to the environment added to `chs-configs`?

## Notes to the tester
_Add any testing hints or instructions here._

2024-01-19 17:17 UTC, ch-code-analysis commented
CI: No security warnings found

2024-01-19 18:05 UTC, johncook-ch requested changes

2024-01-22 09:35 UTC, crowlandsCH commented on src/main/resources/transform_rules.yml
> +      data.description_values.psc_name: '[% originalValues.pscName | title_case  %]'
ahh so I was right the first time not to apply it to those. Will fix now.

2024-01-22 11:33 UTC, ch-code-analysis commented
CI: No security warnings found

2024-01-24 12:00 UTC, cgregoryCH approved these changes

2024-01-24 12:01 UTC, sthompsonCH approved these changes

2024-01-24 13:24 UTC, merged