DSND-2138: Transform FH delta to child api request
companieshouse/filing-history-delta-consumer pull request #51
Opened 2024-03-28 14:35 UTC by sthompsonCH

## Describe the changes

### Related Jira tickets
[DSND-2138](https://companieshouse.atlassian.net/browse/DSND-2138)

## Developer check list
### General
- [ ] Is the PR as small as it can be?
- [ ] Has the Jira ticket been updated with any relevant comments?
- [ ] Is the `README` up to date?
- [ ] Has the `POM` been updated for the latest versions of dependencies?
- [ ] Has the code been double-checked against `main`?
- [ ] Does the code adhere standards in this repository, including SonarQube checks?

### Testing
- [ ] Do the code changes have unit and integration tests with code coverage > 80%?
- [ ] Has the code been tested locally and/or passed the API Karate tests on Tilt?
- [ ] Have mandatory manual test cases been run?
- [ ] Are extra Karate tests required?
- [ ] Are all the test data resources up to date?

### Release preparation
_Where possible, add links to the respective Jira tickets when an item is checked_
- [ ] Have these changes been included in a release ticket?
- [ ] Are changes required to the `docker-chs-development` deployment or test data?
- [ ] Are any changes required to the environment added to `chs-configs`?

## Notes to the tester
_Add any testing hints or instructions here._

2024-04-04 16:52 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-04-04 17:21 UTC, ch-code-analysis commented
CI: No security warnings found

2024-04-05 14:20 UTC, ch-code-analysis commented
CI: No security warnings found

2024-04-08 11:37 UTC, kinpang-CH approved these changes

2024-04-09 10:45 UTC, johncook-ch requested changes

2024-04-09 10:45 UTC, johncook-ch commented on src/main/java/uk/gov/companieshouse/filinghistory/consumer/mapper/InternalFilingHistoryApiMapper.java
> +                    LOGGER.error("Null transaction kind result provided");
`DataMapHolder.getLogMap()` missing

2024-04-09 10:45 UTC, johncook-ch commented on src/main/java/uk/gov/companieshouse/filinghistory/consumer/service/FormTypeConfig.java
> +            LOGGER.error("Blacklist file not found: [%s]".formatted(file));
DataMapHolder.getLogMap()

2024-04-09 13:37 UTC, kinpang-CH approved these changes

2024-04-09 13:40 UTC, ch-code-analysis commented
CI: No security warnings found

2024-04-09 13:41 UTC, johncook-ch submitted a review, later dismissed

2024-04-09 15:41 UTC, kinpang-CH approved these changes

2024-04-09 15:41 UTC, ch-code-analysis commented
CI: No security warnings found

2024-04-09 15:42 UTC, johncook-ch approved these changes

2024-04-09 16:39 UTC, crowlandsCH approved these changes

2024-04-10 08:43 UTC, cgregoryCH approved these changes

2024-04-10 08:55 UTC, merged