DSND-2433: Transform composite resolutions
companieshouse/filing-history-delta-consumer pull request #63
Opened 2024-04-19 14:46 UTC by cgregoryCH

## Describe the changes
* Handles transformation of composite resolutions.
* RES15 not included as it should be handled differently.

### Related Jira tickets
[DSND-2433](https://companieshouse.atlassian.net/browse/DSND-2433)

## Developer check list
### General
- [ ] Is the PR as small as it can be?
- [ ] Has the Jira ticket been updated with any relevant comments?
- [ ] Is the `README` up to date?
- [ ] Has the `POM` been updated for the latest versions of dependencies?
- [ ] Has the code been double-checked against `main`?
- [ ] Does the code adhere standards in this repository, including SonarQube checks?

### Testing
- [ ] Do the code changes have unit and integration tests with code coverage > 80%?
- [ ] Has the code been tested locally and/or passed the API Karate tests on Tilt?
- [ ] Have mandatory manual test cases been run?
- [ ] Are extra Karate tests required?
- [ ] Are all the test data resources up to date?

### Release preparation
_Where possible, add links to the respective Jira tickets when an item is checked_
- [ ] Have these changes been included in a release ticket?
- [ ] Are changes required to the `docker-chs-development` deployment or test data?
- [ ] Are any changes required to the environment added to `chs-configs`?

## Notes to the tester
_Add any testing hints or instructions here._

2024-04-19 15:49 UTC, sthompsonCH approved these changes

2024-04-22 12:44 UTC, crowlandsCH approved these changes

2024-04-22 12:49 UTC, johncook-ch requested changes

2024-04-22 12:49 UTC, johncook-ch commented on src/test/java/uk/gov/companieshouse/filinghistory/consumer/mapper/pretransform/AssociatedFilingNodeMapperTest.java
> +        associatedFilingNodeMapper = new AssociatedFilingNodeMapper(objectMapper, formatDate);
Do we need this? The value can be assigned once in the declaration, assuming the mapper is stateless

2024-04-22 12:49 UTC, johncook-ch commented on src/test/java/uk/gov/companieshouse/filinghistory/consumer/mapper/pretransform/DeltaNodeMapperTest.java
> +        preTransformMapper = new DeltaNodeMapper(objectMapper, formatDate);
Do we need this? The value can be assigned once in the declaration, assuming the mapper is stateless

2024-04-22 12:49 UTC, johncook-ch commented on src/test/java/uk/gov/companieshouse/filinghistory/consumer/mapper/pretransform/EmbeddedChildNodeMapperTest.java
> +        embeddedChildNodeMapper = new EmbeddedChildNodeMapper(objectMapper, formatDate);
Do we need this? The value can be assigned once in the declaration, assuming the mapper is stateless

2024-04-22 12:49 UTC, johncook-ch commented on src/test/java/uk/gov/companieshouse/filinghistory/consumer/mapper/pretransform/ResolutionNodeMapperTest.java
> +        resolutionNodeMapper = new ResolutionNodeMapper(objectMapper, formatDate);
Do we need this? The value can be assigned once in the declaration, assuming the mapper is stateless

2024-04-22 12:52 UTC, johncook-ch commented on src/test/java/uk/gov/companieshouse/filinghistory/consumer/mapper/pretransform/AssociatedFilingNodeMapperTest.java
> +        associatedFilingNodeMapper = new AssociatedFilingNodeMapper(objectMapper, formatDate);
@cgregoryCH explained that this fixes a mock ordering issue

2024-04-22 12:52 UTC, johncook-ch commented on src/test/java/uk/gov/companieshouse/filinghistory/consumer/mapper/pretransform/EmbeddedChildNodeMapperTest.java
> +        embeddedChildNodeMapper = new EmbeddedChildNodeMapper(objectMapper, formatDate);
@cgregoryCH explained that this fixes a mock ordering issue

2024-04-22 12:53 UTC, johncook-ch commented on src/test/java/uk/gov/companieshouse/filinghistory/consumer/mapper/pretransform/ResolutionNodeMapperTest.java
> +        resolutionNodeMapper = new ResolutionNodeMapper(objectMapper, formatDate);
@cgregoryCH explained that this fixes a mock ordering issue

2024-04-22 12:53 UTC, johncook-ch commented on src/test/java/uk/gov/companieshouse/filinghistory/consumer/mapper/pretransform/DeltaNodeMapperTest.java
> +        preTransformMapper = new DeltaNodeMapper(objectMapper, formatDate);
@cgregoryCH explained that this fixes a mock ordering issue

2024-04-22 12:53 UTC, johncook-ch approved these changes

2024-04-22 13:00 UTC, merged